name: Update domains

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 4,16 * * *"
  workflow_dispatch: {}

jobs:
  update:
    name: Update domains
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Git
        working-directory: ./gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update domain numbers
        env:
          JM_PROXY: ${{ secrets.JM_PROXY }}
          JM_PROXY_PATH: ${{ secrets.JM_PROXY_PATH }}
        working-directory: ./gh-pages
        run: python3 ../main.py

      - name: Push changes
        if: always()
        working-directory: ./gh-pages
        run: git push
