name: Update domains

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 4,16 * * *"
  workflow_dispatch: {}

jobs:
  update:
    name: Update domains
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Git
        working-directory: ./gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update NewToki domain number
        working-directory: ./gh-pages
        run: python3 ../newtoki.py

      - name: Update Toonkor domain number
        working-directory: ./gh-pages
        run: python3 ../toonkor.py

      - name: Update Zerobyw domain
        working-directory: ./gh-pages
        run: python3 ../zerobyw.py

      - name: Update WNACG domains
        working-directory: ./gh-pages
        run: python3 ../wnacg.py

      - name: Update JM domains
        working-directory: ./gh-pages
        run: python3 ../jmcomic.py

      - name: Push changes
        if: always()
        working-directory: ./gh-pages
        run: git push
